server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost/users_service
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    user:
      name: jose
      password: 123
  jwt:
    secret: ${secret}
  logging:
    level:
      org:
        springframework:
          security: TRACE